### ISSUE TITLE
Time-out on multiChannelNodeId

### ISSUE THREAD

**Issue by StraDijk** [athombv/node-homey-zwavedriver#12]
Time-out error trying to get data from channels. The code did work several weeks ago.

Code used:
`measure_power: {
            multiChannelNodeId: 1,
            command_class: 'COMMAND_CLASS_METER',
            command_get: 'METER_SUPPORTED_GET',
            command_report: 'METER_SUPPORTED_REPORT',
        },`

New debug log:
`[debug] 1 COMMAND_CLASS_METER METER_SUPPORTED_GET args: {} err: { [Error: timeout] message: 'timeout' } result: null
`

Old debug log same code:
`[debug] 1 COMMAND_CLASS_METER METER_SUPPORTED_GET args: { Properties1: { 'Rate Type': '3', Scale: 0 }, 'Scale 2': 0 } err: null result: { 'Properties1 (Raw)': <Buffer 61>,
  Properties1:
   { 'Meter Reset': false,
     'Meter Type': 'Electric meter',
     'Rate Type': 'Import and Export' },
  'Properties2 (Raw)': <Buffer 05>,
  Properties2: { 'Scale Supported 0': 5, 'M.S.T': false } }`

**Comment by caseda** [comment]
Not related, Meter CC just times out from time to time.

Does it show both end Nodes in the debug?
or just end node 1

Does it also happen if you leave away the Meter CC in endnode 1?
maybe we need to add a small timeout when multiple Meter CC commands are being called.

**Comment by alledijkstra** [comment]
It shows only channel 0. Channels 1,2 and 3 time-out.

Will try later without Meter CC.

**Comment by caseda** [comment]
channel 0? i don't know any devices that use endnode 0

what device are we talking about? model number etc

**Comment by alledijkstra** [comment]
BeNext P1 Dongle

I recieved the following information from benext:
`Kanaal 0
- Wattage
  - METER_REPORT zonder ratetype (reserved) (teruglevering wordt bepaald a.d.h.v. negatieve signed waarden)
- kWh van verbruikte energie
  - METER_REPORT met ratetype 1 (used)

Z-Wave Kanaal 1 (energie hoog tarief )
- Wattage verbruikte energie
  - METER_REPORT met ratetype 1 (import)
- Wattage opgewekte energie
  - METER_REPORT met ratetype 2 (export)
- kWh van verbruikte energie
  - METER_REPORT met ratetype 1 (import)
- kWh van teruggeleverde energie
  - METER_REPORT met ratetype 2 (export)

Z-Wave Kanaal 2 (energie laag tarief )
- Wattage verbruikte energie
  - METER_REPORT met ratetype 1 (import)
- Wattage opgewekte energie
  - METER_REPORT met ratetype 2 (export)
- kWh van verbruikte energie
  - METER_REPORT met ratetype 1 (import)
- kWh van teruggeleverde energie
  - METER_REPORT met ratetype 2 (export)

Z-Wave Kanaal 3 (gasstanden)
- totaal m3 stand
  - METER_REPORT`

**Comment by caseda** [comment]
this issue can be closed, someone made it work with the p1 dongle
https://github.com/ajterpstra/eu.benext
