### ISSUE TITLE
Add device unavailable for battery device when it does not respons on wake up

### ISSUE THREAD

**Issue by RobinBol** [athombv/node-homey-zwavedriver#13]
When a battery device is offline, battery dead, or broken for some other reason, it would be nice that Homey marks this device as unavailable.

**Comment by WeeJeWel** [comment]
The question is - how to determine it's dead?

**Comment by caseda** [comment]
option:
if 2 times the wake-up value has passed without response (`on.online` trigger) set it unAvailable

**Comment by RobinBol** [comment]
Closing this issue, not likely to be implemented.
