### ISSUE TITLE
read.me installation instructions not working when programmming without git

### ISSUE THREAD

**Issue by nattlip** [athombv/node-homey-zwavedriver#17]
this works  which i found in the fibraro app node modules homey zwave driver read.me

why not mentioned in this read.me ?

cd /path/to/com.your.homeyapp/
npm install --save https://github.com/athombv/node-homey-zwavedriver

**Comment by WeeJeWel** [comment]
We encourage the use of a git submodule to keep the version in sync. Developing without Git is generally a bad idea anyway ;-)

**Comment by nattlip** [comment]
thats only a matter of opnion not a fact . i use  visual studio version control.
