### ISSUE TITLE
Feature request: update default ON / OFF action card to trigger depending on state of the device (or not)

### ISSUE THREAD

**Issue by TedTolboom** [athombv/node-homey-zwavedriver#23]
The standard behavior of a Switch ON action card is to switch ON the device regardless of the state of the device, so it will send a command (and wait for confirmation) before sending the next command...
If you need to switch of 10 devices (of which a number are already off), it will still take some time before all devices are off

I would love an "switch on" /  "switch off" action card which would provide the option to "send command anyway" or "switch on when device is off"... will increase responsiveness

This should be possible for Z-wave, since the state of the device Homey knows should match the state of the device... so Homey should not have to retreive first the actual state from the device but use it's own state (recollection) of the device.

Since this is intercepting the SET command, it should be implemented in the Z-wave driver (not in the device driver).

**Comment by RobinBol** [comment]
It is unfortunately not always the case that Homey knows the correct onoff state of a device. Sometimes they do not respond. When looking at the state before a onoff switch is made it might be possible that the device gets out of sync (e.g. sending an on command when device is actually on but Homey thinks its off and vice versa).

**Comment by RobinBol** [comment]
Will close this issue, as it's implementation might cause more problems when devices get out of sync.
