### ISSUE TITLE
Homey 1.1.4 / zwavedriver 1.1.4: Unable to set the desired and accepted wakeup interval

### ISSUE THREAD

**Issue by TedTolboom** [athombv/node-homey-zwavedriver#29]
Homey 1.1.4 / zwavedriver 1.1.4

While debugging the battery update (getOnWakeUp) function, I typically set the wakeup interval on a relative low (yet still acceptable) level. Around 300 or 600 seconds to see that the automatic interval is also working...

After upgrading the Homey 1.1.4 (and Z-wave driver 1.1.4), I am no longer able to change it to this value... no response.

From @caseda I understood that in this version, some changes / restrictions have been implemented for the wakeup interval (min, max and step size), although I cannot find it in the documentation nor in the settings card of the devices (additional hint connected to this interval), or active validation (and response) of this value (similar to other settings).

Device capabilities:
```
[debug] node.CommandClass['COMMAND_CLASS_WAKE_UP'].on('report') arguments: { '0': { value: 10, name: 'WAKE_UP_INTERVAL_CAPABILITIES_REPORT' },
  '1': 
   { 'Minimum Wake Up Interval Seconds (Raw)': <Buffer 00 01 2c>,
     'Minimum Wake Up Interval Seconds': 300,
     'Maximum Wake Up Interval Seconds (Raw)': <Buffer ff ff f0>,
     'Maximum Wake Up Interval Seconds': 16777200,
     'Default Wake Up Interval Seconds (Raw)': <Buffer 00 a8 c0>,
     'Default Wake Up Interval Seconds': 43200,
     'Wake Up Interval Step Seconds (Raw)': <Buffer 00 00 3c>,
     'Wake Up Interval Step Seconds': 60 },
  '2': null }
```

Setting it to 300 and 360 seconds should be possible.

After setting the wakeup interval to 300 seconds (and proper update procedure, ie. when the device is online), the device still reports the app default value of 21600 seconds (aka not updated):
```
[debug] node.CommandClass['COMMAND_CLASS_WAKE_UP'].on('report') arguments: { '0': { value: 6, name: 'WAKE_UP_INTERVAL_REPORT' },
  '1': 
   { 'Seconds (Raw)': <Buffer 00 54 60>,
     Seconds: 21600,
     'NodeID (Raw)': <Buffer 01>,
     NodeID: 1 },
  '2': null }
```

Tried several times, on 300 and 360, with same response.
Tried on 3600 seconds as interval (same procedure):
```
[debug] node.CommandClass['COMMAND_CLASS_WAKE_UP'].on('report') arguments: { '0': { value: 6, name: 'WAKE_UP_INTERVAL_REPORT' },
  '1': 
   { 'Seconds (Raw)': <Buffer 00 0e 10>,
     Seconds: 3600,
     'NodeID (Raw)': <Buffer 01>,
     NodeID: 1 },
  '2': null }
```

Tried on 7200 seconds as interval (same procedure):
```
[debug] node.CommandClass['COMMAND_CLASS_WAKE_UP'].on('report') arguments: { '0': { value: 6, name: 'WAKE_UP_INTERVAL_REPORT' },
  '1': 
   { 'Seconds (Raw)': <Buffer 00 1c 20>,
     Seconds: 7200,
     'NodeID (Raw)': <Buffer 01>,
     NodeID: 1 },
  '2': null }
```
So it appear that there is a different minimum level than specified by the devices capabilities.

Questions I have:
1) What is the mechanism behind the limitations of the wakeup interval; is this based on the device capabilities of are other non-device specific limits introduced?
2) Please update the documentation accordingly.
3) Is it possible to add these limitation to the device settings card, similar to other Z-wave parameters (validation) and the association groups (amount of devices to be added and possibility to add additional hint, app specific)

**Comment by WeeJeWel** [comment]
These values are retrieved from the device and then applied in the front-end. So setting them should always work.. which device are you using?

**Comment by TedTolboom** [comment]
@WeeJeWel these values and issues of not being able to update are retrieved from 2 Neo PIR's...
If helpful, I could do a similar test on the Fibaro PIR's...

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
