### ISSUE TITLE
Homey 1.1.9 / zwavedriver 1.1.4: getOnWakeUp too late or calling battery_get command is incorrect

### ISSUE THREAD

**Issue by TedTolboom** [athombv/node-homey-zwavedriver#30]
** Software version**
Homey v1.1.9, Fibaro app 1.2.2 (GitHub, patched, Z-wave driver included 1.1.4)

** Issue description**
I noticed that with the current release the Fibaro motion sensors (FGMS-001-PLUS), not always provide the motion detection alarm. Checked the capability definition which seems correct.

I also noticed that, unlike the Neo motion sensors, the Fibaro's don't seem to respond to the Battery_get command initiated from the Z-wavedriver based on the online event (aka getOnWakeUp)... 

** Released implementation, 'getOnWakeUp':true in driver.js, GET command by Z-wave driver**

Fibaro app 1.2.2, FGMS-001-PLUS/driver.js:
```
'measure_battery': {
			'getOnWakeUp': true,
			'command_class': 'COMMAND_CLASS_BATTERY',
			'command_get': 'BATTERY_GET',
			'command_report': 'BATTERY_REPORT',
			'command_report_parser': report => {
				if (report['Battery Level'] === "battery low warning") return 1;
				if (report.hasOwnProperty('Battery Level (Raw)'))
					return report['Battery Level (Raw)'][0];
				return null;
			}
		}
```
since adding these 2 motion sensors some days ago and while testing (updating multiple settings), I manually wake-up'd these sensors a dozen timed... and battery-levels were not updated..

some debug logging with 'getOnWakeUp': true,
```
[debug] node.on('online') arguments: { '0': true }
[debug]  COMMAND_CLASS_BATTERY->BATTERY_GET args: {} cb: true
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 07 01 5e 86 72 59 80 73 56 22 31 98 7a> }
[debug] settings() newSettingsObj { motion_sensor_sensitivity: 12,
  ........
  led_indicating_tamper_alarm: false } changedKeysArr [ 'tamper_sensitivity' ]
[debug] CONFIGURATION_SET index: 20 size: 1 newValue <Buffer 14>
[debug] node.on('online') arguments: { '0': false }
[debug] node.on('online') arguments: { '0': true }
[debug]  COMMAND_CLASS_BATTERY->BATTERY_GET args: {} cb: true
[debug] node.CommandClass['COMMAND_CLASS_NOTIFICATION'].on('report') arguments: { '0': { value: 5, name: 'NOTIFICATION_REPORT' },
  '1': 
   { 'V1 Alarm Type (Raw)': <Buffer 00>,
     'V1 Alarm Type': 0,
     'V1 Alarm Level (Raw)': <Buffer 00>,
     'V1 Alarm Level': 0,
     'Reserved (Raw)': <Buffer 00>,
     'Notification Status (Raw)': <Buffer ff>,
     'Notification Status': 'On',
     'Notification Type (Raw)': <Buffer 07>,
     'Notification Type': 'Home Security',
     'Event (Raw)': <Buffer 00>,
     Event: 0,
     'Properties1 (Raw)': <Buffer 01>,
     Properties1: { 'Event Parameters Length': 1, Sequence: false },
     'Event Parameter': <Buffer 03>,
     'Event (Parsed)': 'Event inactive' },
  '2': null }
[debug] node.on('online') arguments: { '0': false }
```

Here, the following response is provided based on every GET command: 
`[debug]  COMMAND_CLASS_BATTERY->BATTERY_GET args: {} cb: true`
So there is a callback, yet no report provided..

Is it possible that this is also blocking other reports from being parsed / received by Homey?

**with listener at driver.js**

With below listener (used for debugging battery powered devices) added to Fibaro app 1.2.2, FGMS-001-PLUS/driver.js
```
module.exports.on('initNode', token => {
    const node = module.exports.nodes[token];
		if (node) {
			node.instance.on('online', online => {
				if (online) {
					// Retrieve 'Battery Level' upon wake-up; temp replacement of getOnWakeUp function (triggering on online event instead of Wake-up)
					node.instance.CommandClass['COMMAND_CLASS_BATTERY'].BATTERY_GET({});
					// Option to retrieve the WAKE_UP_INTERVAL_CAPABILITIES upon wake-up; for debugging only
					// node.instance.CommandClass['COMMAND_CLASS_WAKE_UP'].WAKE_UP_INTERVAL_CAPABILITIES_GET({});
					// Option to retrieve the WAKE_UP_INTERVAL upon wake-up; for debugging only
					// node.instance.CommandClass['COMMAND_CLASS_WAKE_UP'].WAKE_UP_INTERVAL_GET({});
					// Option to retrieve configuration of a certain parameter upon wake-up; for debugging only
					// node.instance.CommandClass['COMMAND_CLASS_CONFIGURATION'].CONFIGURATION_GET(
					// 	{ 'Parameter Number': new Buffer([86])
					// 	}, null);
					// node.instance.CommandClass['COMMAND_CLASS_CONFIGURATION'].CONFIGURATION_GET(
					// 	{'Parameter Number': new Buffer([87])
					//	}, null );
					// node.instance.CommandClass['COMMAND_CLASS_CONFIGURATION'].CONFIGURATION_GET(
					//	{'Parameter Number': new Buffer([89])
					//	}, null );
					// node.instance.CommandClass['COMMAND_CLASS_CONFIGURATION'].CONFIGURATION_GET(
					//	{'Parameter Number': new Buffer([86])
					//	}, null );
					// node.instance.CommandClass['COMMAND_CLASS_ZWAVEPLUS_INFO'].ZWAVEPLUS_INFO_GET({});
				}
			}
		);
		}
}
);
```
With this listener I do get a battery report on every (manual or automatic) wakeup:
```
[debug] node.on('online') arguments: { '0': true }
[debug] node.on('applicationUpdate') arguments: { '0': <Buffer 04 07 01 5e 86 72 59 80 73 56 22 31 98 7a> }
[debug] node.CommandClass['COMMAND_CLASS_BATTERY'].on('report') arguments: { '0': { value: 3, name: 'BATTERY_REPORT' },
  '1': { 'Battery Level (Raw)': <Buffer 64>, 'Battery Level': {} },
  '2': null }
[debug] node.on('online') arguments: { '0': false }
```

If further information is required, let me know.

**Comment by RobinBol** [comment]
Thanks for the elaborate issue! Just one thing that you could try is setting the `command_get_cb: false` flag and see if that fixes things (for for example the `measure_battery` capability), that is the only thing that might differ. The `getOnWakeUp` listens to the same `online` event so that should not be the issue.

**Comment by TedTolboom** [comment]
I was considering that the absence of the command_report_parser to the measure_battery optionsCapabilityItem was the culprit... 

Based on: 
```
// Parse value using command report parser
const value = optionsCapabilityItem.command_report_parser(result, node);
	if (value instanceof Error) return value;
```

and:
```
this._debug(optionsCapabilityItem.multiChannelNodeId || '', `${optionsCapabilityItem.command_class}->${optionsCapabilityItem.command_get}`, 'args:', args, 'cb:', cb !== false);
```

so I added `'command_get_parser': () => ({}),` which did not have the intended effect; no battery reports during wakeup

Following your suggestion, I added `'command_get_cb': false,` which had the desired effect

**Comment by RobinBol** [comment]
Ok that is great, thanks for figuring this out! I guess this will have to be changed for all capabilities and devices for which this is relevant.

**Comment by TedTolboom** [comment]
@RobinBol I would guess that adding this line to surpress the callback function is only a short term containment.

There are more command classes that do not require additional arguments and thus the 'command_get_parser'.. and this particular capability is used by all battery powered Z-wave devices.

So I would recommend to solve this into the Z-wave driver instead of asking all developers to add additional `'command_get_cb': false,` statements. Do you agree?

**Comment by RobinBol** [comment]
I tried to reproduce, but even with command_get_cb -> false, the device does not always report the battery level. Emile investigated this a while back quite thoroughly and seems to a device issue.

**Comment by RobinBol** [comment]
Due to inactivity and the comment above I will close this issue for now.
