### ISSUE TITLE
Homey 1.3.1 - Network Graph in "Stuff for Geeks" keeps animating without reason

### ISSUE THREAD

**Issue by bm480** [athombv/node-homey-zwavedriver#36]
For some unknown reason the nodes in the Network Graph keep switching positions which makes it look like a (very busy) bees hive.

**Comment by caseda** [comment]
They already have a issue in the wait at the creator of the line mesh (it is not their own creation) 

Also already as an issue in homey: https://github.com/athombv/homey/issues/1370

**Comment by RobinBol** [comment]
Will close this issue as it is not related to `zwave-driver` and because duplicate of: https://github.com/athombv/homey/issues/1370
