### ISSUE TITLE
Homey 1.3.1 - Network Graph doesn't show device Zone

### ISSUE THREAD

**Issue by bm480** [athombv/node-homey-zwavedriver#37]
Network Graph doesn't show nodes without device Zone which makes it impossible to distinguish nodes having the same name (eg. each room has a Ceiling Lamp).

**Comment by RobinBol** [comment]
This is not something we will fix, the Desktop app will soon be replaced by a new mobile app, hence fixing this 'bug' does not make any sense. Hope you understand!

**Comment by WeeJeWel** [comment]
We will move the Z-Wave graph to https://developer.athom.com though, so it's a nice suggestion.
