### ISSUE TITLE
compose makes device.js which requiers homey mesh driver and not homey zwave driver

### ISSUE THREAD

**Issue by nattlip** [athombv/node-homey-zwavedriver#64]
'use strict';

const { ZwaveDevice } = require('homey-zwavedriver');  this was homey meshdriver

class MyZWaveDevice extends ZwaveDevice {

async	onNodeInit() {
		this.log('MyZWaveDevice has been inited');

		

	}

}

module.exports = MyZWaveDevice;

**Comment by caseda** [comment]
Compose doesn't touch the device.js
Compose only composes certain files to app.json.

If you mean it installs meshdriver vs zwave driver, then that is based on your SDK version in your app.json and that you have "zwave" in your plugin file, v2 and before installs meshdriver, v3 and up installs z-wave driver as that is really recommended for sdkv3

**Comment by nattlip** [comment]
hoax
