### ISSUE TITLE
homey as secondary controller doesn't work

### ISSUE THREAD

**Issue by sebohans** [athombv/node-homey-zwavedriver#7]
I'm trying to add Homey as a secondary controller to my Homeseer setup.
Unfortunately it fails on a security negotiation.
Is this feature currently not active in Homey fimware 0.9.3?
I succesfully included a vera edge and a domoticz server to my Homeseer as a secondary controller and i can see my z-wave device in there interfaces.
But with Homey I can't see any devices created. And i can't manually add them.
Did someone manage to get this working?

**Comment by RobinBol** [comment]
Hi! Sorry for the late response, just found this issue again. Homey is currently not completely equipped to work as a secondary controller, therefore I'd recommend to use it solely as a primary controller.
